### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by SingleCarbon** [HanzCEO/FaucetPayPHP#1]
Fatal error: Uncaught Error: Method name must be a string in /home/vol16_1/byethost12.com/b12_28631978/htdocs/İndex.php:8 Stack trace: #0 {main} thrown in /home/vol16_1/byethost12.com/b12_28631978/htdocs/İndex.php on line 8

I'm getting method error, can you help me?

**Comment by Sparkmusic** [comment]
Highest paying unlimited tron faucet ...chance to win 100 trx 
Site link : http://dlrtronfaucet.co.in/
